### ISSUE TITLE
Deprecated extensions/code tracking

### ISSUE THREAD

**Issue by WyohKnott** [new-xkit/XKit#178]
Can I open this so your team can track deprecated code. For example:
- [x] Reblog as text is not needed anymore since Tumblr has finally changed this behavior
- [x] The Dashboard GL fix is not working anymore since Tumblr implemented the "moving avatars" along the post, and I don't think it's useful anymore (for ref http://xkit-extension.tumblr.com/post/61016195061/xkit-dashboardgl)
- [x] Atesh had left the extension pack code, but it was not used anymore since, if I recall correctly, he was afraid of security issues (distributing unchecked extensions, among an user base not tech savyy and prone to prone to be target of spam). Unless we plan to revive the concept of extension pack, it's safe to get rid of it.

**Comment by AprilSylph** [comment]
resolved by #320, #484 and #1529
