### ISSUE TITLE
Release Safari version

### ISSUE THREAD

**Issue by 0xazure** [new-xkit/XKit#572]
Meta-issue tracking the release of the Safari version

- [x] Merge in @hobinjk's changes to Safari (#574)
- [x] Create build scripts to build the extension from source (#546)
- [x] Remove the 'unsupported' warning from `xkit_preferences` (#571)
- [x] Rebuild `dist/` with the above changes
- [x] Draft release announcement post
- [x] Submit to the [Safari Extension Store](https://extensions.apple.com/)

**Comment by nb622** [comment]
@NewXKit
nb62284: Welcome to the Live Support for New XKit. If you did not yet set a username, please use /nick <Username> to do so. 
nb62284
hey - a couple of you guys helped me last night and also sent me the link on github for the new safari extension - which i installed and @hobinjk asked me to let you guys know how it went and if it was working on my computer/imac 
<nightpool> Yeah one sec we made a github issue let me look it up 
 Just put it here for now: https://github.com/new-xkit/XKit/issues/572 
<Wolvan> yep, @hobinjk helped you. Glad it works well for you 
nb62284
oh, well, it doesn't.. 
but it started to seem like it might soon? 
i mean, the extension plugin downloads fine.. it installs itself on the tumblr dash just as in chrome.. 
and it opens the dialog window preference pane 
<Wolvan> but? 
nb62284
its misaligned and the gui is sorta messed up so its hard to read overlapping text; but once i installed it and had some tweaks done it said it updated and installed and to refresh page. 
i got the same new inbox notification bubble at the bottom left corner 
but underneath that was a new warning (!) 
<nightpool> but it might be a bug 
nb62284
which said something like "I'm sorry but safari no longer allows XKit to be used.." 

![2015-10-01_21-09-21](https://cloud.githubusercontent.com/assets/8269881/10249546/e892a082-68f3-11e5-8506-3918b97ee91c.png)
![screen1](https://cloud.githubusercontent.com/assets/8269881/10250225/91658636-68f7-11e5-8c8e-8e02277b86ed.png)

<nightpool> Yep that’s a old warning 
<nightpool> it doesn’t affect anything else 
<Wolvan> we have a PR that fixes that already 
<nightpool> and we’ll be removing it soon 
<nightpool> (yeah) 
nb62284
so when i pressed OK, i then refreshed page and no warning came back; it appeared fine in the dash, and so i clicked on blog to open in the sidebar drawer and then i attempted to use {one-click postage} for a photo reblog
nb62284
it looked like it worked but the ajaxloader just looped infinitely (attached mp4 of screen shot and have a gif too i think)
nb62284
no green confirmation or error etc 
<nightpool> Hmm. nb62284, does one click reblog work on the dash (not in the sidebar viewer?) 
nb62284
no, same - doesn't seem to actually progress, operation never completes 
<Wolvan> can you check the JS console? 
<Wolvan> @nightpool how do you open the console on safari 
nb62284
sure, i had a look - go to pref and click 'developer' in menu 
once thats on you can choose to check encoding and decoding 
<nightpool> hmmmmm 
<nightpool> this is interesting. 
<nightpool> nb62284: what version of safari do you have? 
nb62284
Version 9.0 (11601.1.56) 
<nightpool> I’m wondering exactly how you’re getting OCR to run in the sidebar 
<nightpool> but that’s like tangential to the current problem so I’ll shelve that for now 
<nightpool> Are you seeing any errors after you click “reblog” or queue or whatgver? 
<nightpool> [edit] Are you seeing any errors after you click “reblog” or queue or whatever?  
nb62284
no, no errors aside from the one warning and the pop up 
<nightpool> I meant in the JS console. 
<nightpool> not on the screen 
<nightpool> like this 
<nightpool> [![blob](https://files.gitter.im/new-xkit/support/NkHA/thumb/blob.png)](https://files.gitter.im/new-xkit/support/NkHA/blob) 
<Wolvan>  @nightpool does xkit_preferences DISABLE xkit if safari is found? 
<nightpool> no @Wolvan I can't imagine so 
nb62284
i don't see any errors 
@NewXKit
<nightpool> otherwise how is @hobinjk developing it/how did would it get tested? 
<nightpool> [edit] @wolvan otherwise how is @hobinjk developing it/how did would it get tested? 
<Wolvan> good point 
<nightpool> okay well if you can fill all this stuff into a [github issue](https://github.com/new-xkit/issues/new) that'd be great 
nb62284
ok ill do that now 
<nightpool> I'll try to get it working as soon as I get a safari dev enviroment set up. 
nb62284
hope this helps 
![2015-10-02 11_18_01](https://cloud.githubusercontent.com/assets/8269881/10250170/4d0a2c76-68f7-11e5-93e7-3867dcb25b31.gif)

**Comment by hobinjk** [comment]
See pull #574 for initial code and way too many manually copied files.

**Comment by hobinjk** [comment]
The infinite looping in OCR appears to not be occurring anymore, `dist/` has already been rebuilt with #571. All that remains is drafting an announcement post and submitting to the store

**Comment by 0xazure** [comment]
@hobinjk any movement on getting submitted to the Safari store?

**Comment by hobinjk** [comment]
@0xazure Just submitted today and "We will review your extension and email you soon at new.xkit@gmail.com."

**Comment by Wolvan** [comment]
We have an email now?!

**Comment by hobinjk** [comment]
@Wolvan Yes, its current uses are for the Apple and Opera store accounts (we are probably not going to publish to the Opera store in the near future). Migration of the Chrome and Firefox store accounts to use it will happen eventually.

**Comment by Wolvan** [comment]
@hobinjk should I switch @NewXKitBot's mail to the new.xkit@gmail.com email as well later on?

**Comment by hobinjk** [comment]
@Wolvan That would be definitely be a good feature to have in the future

**Comment by rpowelll** [comment]
Has there been any movement on this in the past few weeks?

**Comment by 0xazure** [comment]
We were waiting on #681 to get closed (which is has been, see #690).  I suspect we'll need to re-submit for review now that we've enabled automatic updating? @hobinjk can you confirm?

@rpowelll sorry, we should have done a better job of inter-linking these issues.

**Comment by nightpool** [comment]
yeah we re-submitted to the store today, hoping to hear back soon

**Comment by hobinjk** [comment]
We did re-submit to the store today, didn't realize I told anyone

**Comment by nightpool** [comment]
you mentioned it in chat I think? not sure where I picked it up

**Comment by hobinjk** [comment]
Apple should tell us what they think within around a week.

**Comment by rpowelll** [comment]
Good to hear!

**Comment by sdaitzman** [comment]
:+1:

**Comment by hobinjk** [comment]
Update from Apple, "2.14 Bad Package," saying to "Please build your Safari Extension with Safari 9 on Yosemite or El Capitan," which is what was done. I'm going to scrap all of the plist files and recreate the extension from scratch to see if this fixes the issue.

**Comment by sdaitzman** [comment]
Thanks :smile:

**Comment by sdaitzman** [comment]
Hey, is this still in progress? Can we help in any way?

**Comment by Wolvan** [comment]
No. Apple is reviewing the extension and until then, there's nothing any of us can do

**Comment by sdaitzman** [comment]
OK thanks for letting me know :smile:

**Comment by sdaitzman** [comment]
Are they still reviewing it?

**Comment by Wolvan** [comment]
To our knowledge, yeah

**Comment by nightpool** [comment]
this was done a long time ago FYI
