### ISSUE TITLE
Future Plans for Pokés

### ISSUE THREAD

**Issue by Wolvan** [new-xkit/XKit#855]
Centralizing the future plans for Pokés here instead of having them as seperate issues

Last updated: 12/07/2015
- [ ] Add Shiny Pokémon (#848)
   - [ ] Have a chance of 1:4096 to spawn a shiny Pokémon.
   - [ ] Show that a Pokémon is shiny with a star or similar symbol
   - [ ] Maybe create sprites for shiny Pokémon later
- [ ] Add counter that shows how many Pokémon you already have of how many there actual are (#847, fixed by #850)
- [ ] Allow Sorting of Pokémon
   - [ ] Sort alphabetically (A-Z)
   - [ ] Sort reverse alphabetically (Z-A)
   - [ ] Sort by Pokémon ID (0-900) in pokedex.json
   - [ ] Sort by reverse Pokémon ID (900-0) in pokedex.json
   - [ ] Sort by ID in official Pokédex
   - [ ] Sort by reverse ID in official Pokédex
   - [ ] Sort by time caught (First caught, first appearing)
   - [ ] Sort by reverse time caught (First caught, last appearing)
- [ ] Give Nickname to Pokémon
- [ ] Release Pokémon
- [ ] Create Pokémon Team
    - [ ] Decide on up to 6 Pokémon
    - [ ] Generate Pokémon Team Trainer Pass ([Example Trainer Pass](http://pokecharms.com/data/attachment-files/2015/12/251308_trainercard-tojou.png))
    - [ ] Allow posting of Trainer Pass
    - [ ] Maybe show Pokémon in your team somewhere on your dashboard
- [ ] Refactor Pokés interface (see #854)
- [ ] "Networked" features
   - [ ] Wondertrading
   - [ ] Trading Offers
   - [ ] Realtime Trading
   - [ ] Battling

If there are any other suggestions or ideas for Pokés, please discuss them here. I will update the list accordingly

**Comment by bvtsang** [comment]
As far as I can tell, there are a lot of requirements for implementing battling:

- a reliable way to communicate with other Pokés players
  - initiating a battle with another player
  - accepting or declining a challenge
  - implementation detail ideas
    - research Tumblr Messaging?
    - set up our own servers?
- hit points
- moves
  - [Power Points](http://bulbapedia.bulbagarden.net/wiki/Power_Point)
  - Does this imply [Pokémon Centers](http://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_Center)?
  - Will we allow players to battle multiple opponents simultaneously? For example, can Brock have separate battles with Ash and Misty at the same time? If so, how does that affect Power Points?
- levels?
  - so that Pokémon can learn new moves
  - implies that Pokémon can (use items to) evolve
  - or you could just make all Pokémon the same level and do away with this entirely
- stats
- items? (optional, but has its own set of dependencies)
  - a way for players to obtain them (via stores, completing quests, from battling players, etc.)
  - currency/economy, if you're going to implement stores
  - inventories
- battle logic
  - accuracy
  - evasion
  - special moves (e.g. [Rain Dance](http://bulbapedia.bulbagarden.net/wiki/Rain_Dance_(move)), [Dig](http://bulbapedia.bulbagarden.net/wiki/Dig_(move)))
  - [status conditions](http://bulbapedia.bulbagarden.net/wiki/Status_condition)
  - swapping Pokémon mid-battle
- recordings/logs? (optional)
  - so that players can show off (e.g. Ash has logs of his battle so that he can remind Gary who really is the best Pokémon trainer)

**Comment by nightpool** [comment]
So, battles implies that you have to have some sort of standard server
distributing pokemon in a way that it keeps track of, otherwise people
could just make up their own teams out of nothing by hacking (esp when we
implement moves and levels, you could just make a bunch of l99 pokemon and
bowl over everybody else)

Plus you run into the issue of trusted randomness for battle simulation
even above and beyond your teams. What happens when I can say the dice
always roll my way?

**Comment by ThePsionic** [comment]
@ Sorting by ID: Pokémon would need to get a National Pokédex ID to account for formes to be able to group them together.

**Comment by Wolvan** [comment]
@ThePsionic National Pokédex ID sorting could work the same way isotopes on the PSE do: Have the main Pokémon ID sorted and just have every other Pokémon Form have the same ID

Re: Battling
Having a server distribute the Pokémon isn't going to help either. You can just easily hack the storage value itself to cheat Pokémon
Also, for the beginning I would have just used Rock Paper Scissors as battle system until a proper one was implemented
I don't want to rely on Tumblr IM personally, since 1.) Not everyone has them and more importantly 2.) It would clutter up the chat. I talked with @ChuckL about it earlier and he said we could manage to get our own server running on his servers.

**Comment by nightpool** [comment]
@wolvan what? If a server distributes pokemon, it would have a record of
all the pokemon someone should have, so editing the storage wouldn't work...

**Comment by Wolvan** [comment]
So don't ever store Pokemon clientside or what?

**Comment by nightpool** [comment]
Well not the canonical values. obviously you could store a cache of what
pokemon you have, you just can't use client-side values for multi-player
stuff.

**Comment by Wolvan** [comment]
How would we even GIVE pokemon then

**Comment by mikehow1984** [comment]
Your pokemon would be tied to your account. If someone edits their client-side values, it doesn't effect the server-side values. If someone legitly "gets" a Pokemon, it'd be stored client and server-side.

**Comment by nightpool** [comment]
@wolvan I'd be happy to whiteboard implementation details with you at some
point.

**Comment by Wolvan** [comment]
You can still just as easily modify the Pokémon that are spawning though, clicking them would send the server a "XXX caught a Pokémon with these stats!"

**Comment by nightpool** [comment]
@wolvan not if the server generates the pokemon that the client displays?
as I suggested?

**Comment by Wolvan** [comment]
That would be a massive load on a server. But alright. If you want it, I'll see about implementing it

**Comment by nightpool** [comment]
@wolvan its not really about what I want—its about making a multiplayer
system that people can't just hack their way through incredibly trivially.
I don't really care either way, but if you want any kind of balance you'll
have to implement it

**Comment by Wolvan** [comment]
I think we have to look into that once the battle system actually comes up

**Comment by mikehow1984** [comment]
So will the battle/stat system implement IV's and EV's? If so, could the player manually allocate EV's into different stats?

**Comment by Wolvan** [comment]
I honestly haven't thought that far, for now I'd say no, though

**Comment by Wolvan** [comment]
From our inbox:
>Random idea for Pokes: Maybe take a few cues from Super Pokemon Rumble and make battles based off how many 'pokes you have and so on ?

I kind of like the idea, gotta do some more reasearch about it but it could be something we could do
